//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryItPageAspNET.ServiceReference9 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference9.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findParks", ReplyAction="http://tempuri.org/IService1/findParksResponse")]
        string findParks(double latitude, double longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findParks", ReplyAction="http://tempuri.org/IService1/findParksResponse")]
        System.Threading.Tasks.Task<string> findParksAsync(double latitude, double longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findTheaters", ReplyAction="http://tempuri.org/IService1/findTheatersResponse")]
        string findTheaters(double latitude, double longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findTheaters", ReplyAction="http://tempuri.org/IService1/findTheatersResponse")]
        System.Threading.Tasks.Task<string> findTheatersAsync(double latitude, double longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findBusStation", ReplyAction="http://tempuri.org/IService1/findBusStationResponse")]
        string findBusStation(double latitude, double longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findBusStation", ReplyAction="http://tempuri.org/IService1/findBusStationResponse")]
        System.Threading.Tasks.Task<string> findBusStationAsync(double latitude, double longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crimedata", ReplyAction="http://tempuri.org/IService1/crimedataResponse")]
        string crimedata(string city, string stateAbbr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crimedata", ReplyAction="http://tempuri.org/IService1/crimedataResponse")]
        System.Threading.Tasks.Task<string> crimedataAsync(string city, string stateAbbr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crimeCount", ReplyAction="http://tempuri.org/IService1/crimeCountResponse")]
        string crimeCount(string ORI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crimeCount", ReplyAction="http://tempuri.org/IService1/crimeCountResponse")]
        System.Threading.Tasks.Task<string> crimeCountAsync(string ORI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NaturalHazards", ReplyAction="http://tempuri.org/IService1/NaturalHazardsResponse")]
        string NaturalHazards(double latitude, double longitude, int radiusKm, decimal minMag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NaturalHazards", ReplyAction="http://tempuri.org/IService1/NaturalHazardsResponse")]
        System.Threading.Tasks.Task<string> NaturalHazardsAsync(double latitude, double longitude, int radiusKm, decimal minMag);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryItPageAspNET.ServiceReference9.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryItPageAspNET.ServiceReference9.IService1>, TryItPageAspNET.ServiceReference9.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string findParks(double latitude, double longitude) {
            return base.Channel.findParks(latitude, longitude);
        }
        
        public System.Threading.Tasks.Task<string> findParksAsync(double latitude, double longitude) {
            return base.Channel.findParksAsync(latitude, longitude);
        }
        
        public string findTheaters(double latitude, double longitude) {
            return base.Channel.findTheaters(latitude, longitude);
        }
        
        public System.Threading.Tasks.Task<string> findTheatersAsync(double latitude, double longitude) {
            return base.Channel.findTheatersAsync(latitude, longitude);
        }
        
        public string findBusStation(double latitude, double longitude) {
            return base.Channel.findBusStation(latitude, longitude);
        }
        
        public System.Threading.Tasks.Task<string> findBusStationAsync(double latitude, double longitude) {
            return base.Channel.findBusStationAsync(latitude, longitude);
        }
        
        public string crimedata(string city, string stateAbbr) {
            return base.Channel.crimedata(city, stateAbbr);
        }
        
        public System.Threading.Tasks.Task<string> crimedataAsync(string city, string stateAbbr) {
            return base.Channel.crimedataAsync(city, stateAbbr);
        }
        
        public string crimeCount(string ORI) {
            return base.Channel.crimeCount(ORI);
        }
        
        public System.Threading.Tasks.Task<string> crimeCountAsync(string ORI) {
            return base.Channel.crimeCountAsync(ORI);
        }
        
        public string NaturalHazards(double latitude, double longitude, int radiusKm, decimal minMag) {
            return base.Channel.NaturalHazards(latitude, longitude, radiusKm, minMag);
        }
        
        public System.Threading.Tasks.Task<string> NaturalHazardsAsync(double latitude, double longitude, int radiusKm, decimal minMag) {
            return base.Channel.NaturalHazardsAsync(latitude, longitude, radiusKm, minMag);
        }
    }
}
