//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeDataFormsApp.ServiceReference6 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference6.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crimedata", ReplyAction="http://tempuri.org/IService1/crimedataResponse")]
        string crimedata(string city, string stateAbbr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crimedata", ReplyAction="http://tempuri.org/IService1/crimedataResponse")]
        System.Threading.Tasks.Task<string> crimedataAsync(string city, string stateAbbr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crimeCount", ReplyAction="http://tempuri.org/IService1/crimeCountResponse")]
        string crimeCount(string ORI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crimeCount", ReplyAction="http://tempuri.org/IService1/crimeCountResponse")]
        System.Threading.Tasks.Task<string> crimeCountAsync(string ORI);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CrimeDataFormsApp.ServiceReference6.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CrimeDataFormsApp.ServiceReference6.IService1>, CrimeDataFormsApp.ServiceReference6.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string crimedata(string city, string stateAbbr) {
            return base.Channel.crimedata(city, stateAbbr);
        }
        
        public System.Threading.Tasks.Task<string> crimedataAsync(string city, string stateAbbr) {
            return base.Channel.crimedataAsync(city, stateAbbr);
        }
        
        public string crimeCount(string ORI) {
            return base.Channel.crimeCount(ORI);
        }
        
        public System.Threading.Tasks.Task<string> crimeCountAsync(string ORI) {
            return base.Channel.crimeCountAsync(ORI);
        }
    }
}
